-- Create panchang_data table for storing daily Panchang information
CREATE TABLE IF NOT EXISTS panchang_data (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    tithi_name VARCHAR(50) NOT NULL,
    tithi_english VARCHAR(50) NOT NULL,
    tithi_paksha VARCHAR(20) NOT NULL,
    tithi_start TIMESTAMP NOT NULL,
    tithi_end TIMESTAMP NOT NULL,
    tithi_lunar_phase VARCHAR(20),
    nakshatra_name VARCHAR(50) NOT NULL,
    nakshatra_english VARCHAR(50) NOT NULL,
    nakshatra_lord VARCHAR(20) NOT NULL,
    nakshatra_symbol VARCHAR(50) NOT NULL,
    nakshatra_start TIMESTAMP NOT NULL,
    nakshatra_end TIMESTAMP NOT NULL,
    yoga_name VARCHAR(50) NOT NULL,
    yoga_english VARCHAR(50) NOT NULL,
    yoga_end TIMESTAMP NOT NULL,
    karana_name VARCHAR(50) NOT NULL,
    karana_english VARCHAR(50) NOT NULL,
    karana_type VARCHAR(20) NOT NULL,
    hindu_month VARCHAR(30) NOT NULL,
    paksha VARCHAR(20) NOT NULL,
    season VARCHAR(30) NOT NULL,
    vikrama_samvat INTEGER NOT NULL,
    shaka_samvat INTEGER NOT NULL,
    kali_yuga INTEGER NOT NULL,
    sunrise_time TIME NOT NULL,
    sunset_time TIME NOT NULL,
    moonrise_time TIME,
    moonset_time TIME,
    moon_phase VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(date)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_panchang_date ON panchang_data(date);

-- Insert sample data for today
INSERT INTO panchang_data (
    date, tithi_name, tithi_english, tithi_paksha, tithi_start, tithi_end, tithi_lunar_phase,
    nakshatra_name, nakshatra_english, nakshatra_lord, nakshatra_symbol, nakshatra_start, nakshatra_end,
    yoga_name, yoga_english, yoga_end, karana_name, karana_english, karana_type,
    hindu_month, paksha, season, vikrama_samvat, shaka_samvat, kali_yuga,
    sunrise_time, sunset_time, moonrise_time, moonset_time, moon_phase
) VALUES (
    CURRENT_DATE,
    'नवमीं', 'Navami', 'Shukla', 
    '2025-09-30 18:06:00', '2025-10-01 19:01:00', '101°',
    'पू.षाढ़ा', 'PurvaShadha', 'Venus', 'पू.षाढ़ा',
    '2025-09-30 08:01:00', '2025-10-01 09:47:00',
    'अतिगण्ड', 'Atiganda', '2025-10-02 03:38:00',
    'विष्टि', 'Vishti', 'Chara',
    'Ashwin', 'Shukla', 'Varsha (Monsoon)',
    2069, 1934, 5113,
    '06:15:00', '18:30:00', '20:45:00', '09:30:00', 'Waxing Crescent'
) ON CONFLICT (date) DO UPDATE SET
    tithi_name = EXCLUDED.tithi_name,
    tithi_english = EXCLUDED.tithi_english,
    tithi_paksha = EXCLUDED.tithi_paksha,
    tithi_start = EXCLUDED.tithi_start,
    tithi_end = EXCLUDED.tithi_end,
    tithi_lunar_phase = EXCLUDED.tithi_lunar_phase,
    nakshatra_name = EXCLUDED.nakshatra_name,
    nakshatra_english = EXCLUDED.nakshatra_english,
    nakshatra_lord = EXCLUDED.nakshatra_lord,
    nakshatra_symbol = EXCLUDED.nakshatra_symbol,
    nakshatra_start = EXCLUDED.nakshatra_start,
    nakshatra_end = EXCLUDED.nakshatra_end,
    yoga_name = EXCLUDED.yoga_name,
    yoga_english = EXCLUDED.yoga_english,
    yoga_end = EXCLUDED.yoga_end,
    karana_name = EXCLUDED.karana_name,
    karana_english = EXCLUDED.karana_english,
    karana_type = EXCLUDED.karana_type,
    hindu_month = EXCLUDED.hindu_month,
    paksha = EXCLUDED.paksha,
    season = EXCLUDED.season,
    vikrama_samvat = EXCLUDED.vikrama_samvat,
    shaka_samvat = EXCLUDED.shaka_samvat,
    kali_yuga = EXCLUDED.kali_yuga,
    sunrise_time = EXCLUDED.sunrise_time,
    sunset_time = EXCLUDED.sunset_time,
    moonrise_time = EXCLUDED.moonrise_time,
    moonset_time = EXCLUDED.moonset_time,
    moon_phase = EXCLUDED.moon_phase,
    updated_at = CURRENT_TIMESTAMP;
