"use client";

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navbar
    home: "Home",
    kundli: "Kundli",
    horoscope: "Horoscope",
    calendar: "Calendar",
    weather: "Weather",
    astroChat: "Astro Chat",
    about: "About",
    
    // Hero Section
    heroSubtitle: "Cosmic dive into",
    heroTitle: "Nirvana Astro",
    heroDescription: "Unlock the secrets of the stars with personalized astrology, daily horoscopes, and expert guidance.",
    astroBot: "Astro Bot",
    astroKundli: "Astro Kundli",
    
    // Features
    featuresEyebrow: "Offerings",
    featuresTitle: "Astrological Services",
    featuresSubtitle: "Comprehensive tools for your cosmic journey",
    
    // Feature Cards
    personalizedKundli: "Personalized Kundli",
    personalizedKundliDesc: "Generate detailed birth charts with precise planetary positions and house placements.",
    dailyHoroscope: "Daily Horoscope",
    dailyHoroscopeDesc: "Get personalized daily predictions based on your zodiac sign and planetary transits.",
    astroChatFeature: "Astro Chat",
    astroChatDesc: "Connect with certified astrologers for personalized guidance and consultations.",
    compatibility: "Compatibility",
    compatibilityDesc: "Analyze relationship compatibility through detailed synastry and composite charts.",
    panchang: "Panchang",
    panchangDesc: "Access auspicious timings, festivals, and lunar calendar with traditional accuracy.",
    remedies: "Remedies",
    remediesDesc: "Discover personalized remedies, mantras, and gemstone recommendations.",
    learnMore: "Learn more",
    
    // Zodiac Signs
    zodiacEyebrow: "Zodiac",
    zodiacTitle: "Explore the 12 Signs",
    zodiacSubtitle: "Pick a sign to view its daily snapshot",
    aries: "Aries",
    taurus: "Taurus",
    gemini: "Gemini",
    cancer: "Cancer",
    leo: "Leo",
    virgo: "Virgo",
    libra: "Libra",
    scorpio: "Scorpio",
    sagittarius: "Sagittarius",
    capricorn: "Capricorn",
    aquarius: "Aquarius",
    pisces: "Pisces",
    
    // CTA Section
    ctaTitle: "Begin your cosmic journey",
    ctaSubtitle: "Chat with our Astro Bot or generate your Kundli",
    startChat: "Start Chat",
    generateKundli: "Generate Kundli",
    
    // Footer
    footerDescription: "Your gateway to cosmic wisdom. Connect with the stars through personalized astrology, horoscopes, and expert guidance.",
    services: "Services",
    support: "Support",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    faq: "FAQ",
    copyright: "All rights reserved. Explore the cosmos with us!",
    
    // Chat Widget
    cosmicGuide: "Cosmic Guide",
    online: "Online",
    askAboutStars: "Ask about your stars...",
    namasteGreeting: "Namaste! I'm your cosmic guide. Ask me anything about astrology, horoscopes, or your birth chart! ✨",
    
    // About Page
    aboutTitle: "About Nirvana Astro",
    aboutSubtitle: "Your gateway to cosmic wisdom and personalized astrological guidance.",
    missionTitle: "Our Mission",
    missionDescription: "We believe that the stars hold the key to understanding ourselves and our place in the universe. Our mission is to make ancient astrological wisdom accessible to everyone through modern technology.",
    missionPoint1: "Personalized Guidance",
    missionPoint1Desc: "Every reading is tailored to your unique birth chart and life circumstances.",
    missionPoint2: "Expert Astrologers",
    missionPoint2Desc: "Our team consists of certified astrologers with decades of experience.",
    missionPoint3: "Modern Technology",
    missionPoint3Desc: "We combine ancient wisdom with cutting-edge technology for accurate readings.",
    valuesTitle: "Our Values",
    valuesSubtitle: "The principles that guide everything we do at Nirvana Astro.",
    value1Title: "Authenticity",
    value1Desc: "We provide genuine, research-based astrological insights without gimmicks.",
    value2Title: "Accessibility",
    value2Desc: "Making cosmic wisdom available to everyone, regardless of background or experience.",
    value3Title: "Respect",
    value3Desc: "Honoring both ancient traditions and modern scientific understanding.",
    teamTitle: "Meet Our Team",
    teamSubtitle: "The passionate astrologers and developers behind Nirvana Astro.",
    teamMember1: "Dr. Anjali Sharma",
    teamRole1: "Lead Astrologer",
    teamDesc1: "20+ years of experience in Vedic astrology and planetary science.",
    teamMember2: "Michael Johnson",
    teamRole2: "Technology Director",
    teamDesc2: "Expert in AI and machine learning for astrological calculations.",
    teamMember3: "Ravi Kumar",
    teamRole3: "Cultural Advisor",
    teamDesc3: "Specialist in traditional astrological practices and cultural interpretation.",
    aboutCtaTitle: "Ready to Begin Your Journey?",
    aboutCtaSubtitle: "Connect with the stars and discover your cosmic destiny today.",
    spiritualJourney: "Spiritual Journey",
    spiritualJourneyDesc: "Discover the profound connection between cosmic wisdom and spiritual enlightenment through our ancient practices.",
    
    // Contact Us Page
    contactTitle: "Contact Us",
    contactSubtitle: "Get in touch with our cosmic guides for personalized astrological guidance and support.",
    email: "Email",
    phone: "Phone",
    address: "Address",
    sendMessage: "Send Message",
    sendMessageDesc: "Have questions about your cosmic journey? We're here to help guide you through the stars.",
    firstName: "First Name",
    lastName: "Last Name",
    firstNamePlaceholder: "Enter your first name",
    lastNamePlaceholder: "Enter your last name",
    emailPlaceholder: "Enter your email address",
    subject: "Subject",
    subjectPlaceholder: "What can we help you with?",
    message: "Message",
    messagePlaceholder: "Tell us about your cosmic questions...",
    
    // Help Center Page
    helpCenterTitle: "Help Center",
    helpCenterSubtitle: "Find answers to your questions and get the support you need for your cosmic journey.",
    frequentlyAskedQuestions: "Frequently Asked Questions",
    faqSubtitle: "Find quick answers to common questions about our astrological services.",
    stillNeedHelp: "Still Need Help?",
    contactSupportDesc: "Can't find what you're looking for? Our cosmic support team is here to help you navigate the stars.",
    emailSupport: "Email Support",
    
    // FAQ Content
    faq1Question: "How accurate are your astrological predictions?",
    faq1Answer: "Our predictions are based on traditional Vedic astrology principles combined with modern astronomical data. While we strive for accuracy, astrology is a guidance tool and should be used alongside your own intuition and decision-making.",
    faq2Question: "What information do I need to provide for a Kundli analysis?",
    faq2Answer: "For an accurate Kundli analysis, we need your date of birth, time of birth, and place of birth. The more precise the birth time, the more accurate your chart will be.",
    faq3Question: "How often should I check my horoscope?",
    faq3Answer: "Daily horoscopes provide general guidance for the day. For major life decisions, we recommend consulting your detailed birth chart and considering planetary transits.",
    faq4Question: "Can I get a consultation with a real astrologer?",
    faq4Answer: "Yes! We offer personalized consultations with certified Vedic astrologers. You can book a session through our contact form or chat with our AI cosmic guide for immediate assistance.",
    faq5Question: "Is my personal information secure?",
    faq5Answer: "Absolutely. We use industry-standard encryption to protect your personal data and birth information. Your privacy is our top priority.",
    faq6Question: "What is the difference between Vedic and Western astrology?",
    faq6Answer: "Vedic astrology uses the sidereal zodiac and focuses on the Moon's position, while Western astrology uses the tropical zodiac. Vedic astrology is more traditional and spiritually oriented.",
    faq7Question: "How do I interpret my birth chart?",
    faq7Answer: "Our detailed Kundli analysis provides explanations for each planet's position and influence. We also offer guided interpretations to help you understand your cosmic blueprint.",
    faq8Question: "Can astrology predict the future?",
    faq8Answer: "Astrology provides insights into potential trends and influences, but it doesn't predict fixed outcomes. It's a tool for understanding cosmic energies and making informed decisions.",
    
    // Privacy Policy Page
    privacyPolicyTitle: "Privacy Policy",
    privacyPolicySubtitle: "Your privacy is important to us. Learn how we collect, use, and protect your personal information.",
    lastUpdated: "Last Updated",
    informationWeCollect: "Information We Collect",
    informationWeCollectDesc: "We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support.",
    personalInfo: "Personal information (name, email, birth details)",
    usageData: "Usage data and service interactions",
    cookiesData: "Cookies and similar tracking technologies",
    communicationData: "Communications with our support team",
    howWeUseInfo: "How We Use Your Information",
    howWeUseInfoDesc: "We use the information we collect to provide, maintain, and improve our astrological services.",
    serviceProvision: "Provide personalized astrological services",
    communication: "Communicate with you about our services",
    improvement: "Improve and develop new features",
    legalCompliance: "Comply with legal obligations",
    dataProtection: "Data Protection",
    dataProtectionDesc: "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.",
    encryption: "End-to-end encryption for sensitive data",
    secureServers: "Secure servers with regular security updates",
    accessControl: "Limited access to authorized personnel only",
    regularAudits: "Regular security audits and assessments",
    yourRights: "Your Rights",
    yourRightsDesc: "You have certain rights regarding your personal information, including the right to access, correct, or delete your data.",
    accessData: "Access your personal data",
    correctData: "Correct inaccurate information",
    deleteData: "Delete your account and data",
    dataPortability: "Export your data in a portable format",
    privacyContactDesc: "If you have any questions about this Privacy Policy, please contact us.",
    
    // Terms of Service Page
    termsOfServiceTitle: "Terms of Service",
    termsOfServiceSubtitle: "Please read these terms carefully before using our astrological services.",
    acceptanceOfTerms: "Acceptance of Terms",
    acceptanceOfTermsDesc: "By accessing and using Nirvana Astro services, you accept and agree to be bound by the terms and provision of this agreement.",
    serviceDescription: "Service Description",
    serviceDescriptionDesc: "Nirvana Astro provides astrological services including horoscope readings, Kundli analysis, and cosmic guidance through our digital platform.",
    astrologicalServices: "Personalized horoscope readings",
    horoscopeReadings: "Daily, weekly, and monthly predictions",
    kundliAnalysis: "Detailed birth chart analysis",
    cosmicGuidance: "AI-powered astrological consultations",
    userObligations: "User Obligations",
    userObligationsDesc: "Users are responsible for providing accurate information and using our services in accordance with these terms.",
    accurateInfo: "Provide accurate birth information",
    respectfulUse: "Use services respectfully and responsibly",
    noMisuse: "Not misuse or abuse our platform",
    complianceWithLaws: "Comply with applicable laws and regulations",
    limitationOfLiability: "Limitation of Liability",
    limitationOfLiabilityDesc: "Our astrological services are for guidance purposes only. We are not liable for any decisions made based on our predictions or advice.",
    modifications: "Modifications",
    modificationsDesc: "We reserve the right to modify these terms at any time. Continued use of our services constitutes acceptance of any changes.",
    termsContactDesc: "If you have questions about these Terms of Service, please contact us.",
    
    // AstroClock Page
    astroClock: "Astro Clock",
    astroClockTitle: "Hindu Time Clock",
    astroClockSubtitle: "Traditional Vedic timekeeping with Ghati, Pal, and Vipal measurements.",
    currentAstrologicalTime: "Current Hindu Time",
    realTimePlanetaryPositions: "Real-time Vedic time calculations",
    darkMode: "Dark Mode",
    hinduPeriods: "Hindu Periods",
    dayNight: "Day/Night",
    digitalTime: "Digital Time",
    ghatiPalVipal: "Ghati:Pal:Vipal",
    currentPeriod: "Current Period",
    sunriseUjjain: "Sunrise (Ujjain)",
    vedicTimeSystem: "Vedic Time System",
    vedicTimeSystemDesc: "Traditional Hindu timekeeping using Ghati (24 minutes), Pal (24 seconds), and Vipal (0.4 seconds) based on sunrise calculations.",
    ujjainCoordinates: "Ujjain Coordinates",
    ujjainCoordinatesDesc: "Calculated for Ujjain (23.1793°N, 75.784912°E), the traditional center of Hindu astrology and timekeeping.",
    sacredTimePeriods: "Sacred Time Periods",
    sacredTimePeriodsDesc: "Eight traditional Hindu time periods from Ushaa (dawn) to Triyaama (late night), each with specific spiritual significance for rituals and meditation.",
    ushaa: "Ushaa",
    purvaanha: "Purvaanha",
    madhyaanha: "Madhyaanha",
    aparaahnha: "Aparaahnha",
    saayankala: "Saayankala",
    pradosha: "Pradosha",
    nishitha: "Nishitha",
    triyaama: "Triyaama",
    dawn: "Dawn",
    morning: "Morning",
    midday: "Midday",
    afternoon: "Afternoon",
    evening: "Evening",
    dusk: "Dusk",
    midnight: "Midnight",
    lateNight: "Late Night",
    angles: "Angles",
    sunPosition: "Sun Position",
    sunPositionDesc: "Current position of the Sun in the zodiac and its astrological significance.",
    moonPhase: "Moon Phase",
    moonPhaseDesc: "Current lunar phase and its influence on cosmic energies and emotions.",
    planetaryTransits: "Planetary Transits",
    planetaryTransitsDesc: "Real-time positions of all planets and their current astrological influences."
  },
  
  ne: {
    // Navbar
    home: "गृह",
    kundli: "कुण्डली",
    horoscope: "राशिफल",
    calendar: "पात्रो",
    weather: "मौसम",
    astroChat: "ज्योतिष च्याट",
    about: "बारेमा",
    
    // Hero Section
    heroSubtitle: "ब्रह्माण्डीय गोता",
    heroTitle: "निर्वाण ज्योतिष",
    heroDescription: "व्यक्तिगत ज्योतिष, दैनिक राशिफल र विशेषज्ञ मार्गदर्शनको साथ ताराहरूका रहस्यहरू खोल्नुहोस्।",
    astroBot: "ज्योतिष बोट",
    astroKundli: "ज्योतिष कुण्डली",
    
    // Features
    featuresEyebrow: "सेवाहरू",
    featuresTitle: "ज्योतिषीय सेवाहरू",
    featuresSubtitle: "तपाईंको ब्रह्माण्डीय यात्राका लागि व्यापक उपकरणहरू",
    
    // Feature Cards
    personalizedKundli: "व्यक्तिगत कुण्डली",
    personalizedKundliDesc: "सटीक ग्रह स्थिति र घरको स्थानसहित विस्तृत जन्म कुण्डली उत्पादन गर्नुहोस्।",
    dailyHoroscope: "दैनिक राशिफल",
    dailyHoroscopeDesc: "तपाईंको राशि र ग्रहीय पारगमनको आधारमा व्यक्तिगत दैनिक भविष्यवाणीहरू प्राप्त गर्नुहोस्।",
    astroChatFeature: "ज्योतिष च्याट",
    astroChatDesc: "व्यक्तिगत मार्गदर्शन र परामर्शका लागि प्रमाणित ज्योतिषीहरूसँग जोडिनुहोस्।",
    compatibility: "अनुकूलता",
    compatibilityDesc: "विस्तृत सिनास्ट्री र कम्पोजिट कुण्डली मार्फत सम्बन्ध अनुकूलताको विश्लेषण गर्नुहोस्।",
    panchang: "पञ्चाङ्ग",
    panchangDesc: "पारम्परिक सटीकतासहित शुभ समय, पर्वहरू र चन्द्र पात्रो पहुँच गर्नुहोस्।",
    remedies: "उपचारहरू",
    remediesDesc: "व्यक्तिगत उपचारहरू, मन्त्रहरू र रत्न सुझावहरू खोज्नुहोस्।",
    learnMore: "थप जान्नुहोस्",
    
    // Zodiac Signs
    zodiacEyebrow: "राशि",
    zodiacTitle: "१२ राशिहरू अन्वेषण गर्नुहोस्",
    zodiacSubtitle: "यसको दैनिक स्न्यापशट हेर्नको लागि एउटा राशि छान्नुहोस्",
    aries: "मेष",
    taurus: "वृष",
    gemini: "मिथुन",
    cancer: "कर्क",
    leo: "सिंह",
    virgo: "कन्या",
    libra: "तुला",
    scorpio: "वृश्चिक",
    sagittarius: "धनु",
    capricorn: "मकर",
    aquarius: "कुम्भ",
    pisces: "मीन",
    
    // CTA Section
    ctaTitle: "तपाईंको ब्रह्माण्डीय यात्रा सुरु गर्नुहोस्",
    ctaSubtitle: "हाम्रो ज्योतिष बोटसँग च्याट गर्नुहोस् वा आफ्नो कुण्डली उत्पादन गर्नुहोस्",
    startChat: "च्याट सुरु गर्नुहोस्",
    generateKundli: "कुण्डली उत्पादन गर्नुहोस्",
    
    // Footer
    footerDescription: "तपाईंको ब्रह्माण्डीय ज्ञानको द्वार। व्यक्तिगत ज्योतिष, राशिफल र विशेषज्ञ मार्गदर्शनको माध्यमबाट ताराहरूसँग जोडिनुहोस्।",
    services: "सेवाहरू",
    support: "सहयोग",
    helpCenter: "सहयोग केन्द्र",
    contactUs: "हामीलाई सम्पर्क गर्नुहोस्",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा सर्तहरू",
    faq: "बारम्बार सोधिने प्रश्नहरू",
    copyright: "सबै अधिकार सुरक्षित। हामीसँग ब्रह्माण्ड अन्वेषण गर्नुहोस्!",
    
    // Chat Widget
    cosmicGuide: "ब्रह्माण्डीय गाइड",
    online: "अनलाइन",
    askAboutStars: "तपाईंका ताराहरूको बारेमा सोध्नुहोस्...",
    namasteGreeting: "नमस्ते! म तपाईंको ब्रह्माण्डीय गाइड हुँ। ज्योतिष, राशिफल वा तपाईंको जन्म कुण्डलीको बारेमा केही पनि सोध्नुहोस्! ✨",
    
    // About Page
    aboutTitle: "निर्वाण ज्योतिषको बारेमा",
    aboutSubtitle: "तपाईंको ब्रह्माण्डीय ज्ञान र व्यक्तिगत ज्योतिषीय मार्गदर्शनको द्वार।",
    missionTitle: "हाम्रो मिशन",
    missionDescription: "हामी विश्वास गर्छौं कि ताराहरूले आफ्नो र ब्रह्माण्डमा हाम्रो स्थान बुझ्नको लागि कुञ्जी राख्छन्। हाम्रो मिशन प्राचीन ज्योतिषीय ज्ञानलाई आधुनिक प्रविधिको माध्यमबाट सबैको लागि सुलभ बनाउनु हो।",
    missionPoint1: "व्यक्तिगत मार्गदर्शन",
    missionPoint1Desc: "हरेक पढाइ तपाईंको अनूठा जन्म कुण्डली र जीवन परिस्थितिहरूको अनुसार तयार गरिन्छ।",
    missionPoint2: "विशेषज्ञ ज्योतिषीहरू",
    missionPoint2Desc: "हाम्रो टोलीमा दशकौंको अनुभव भएका प्रमाणित ज्योतिषीहरू छन्।",
    missionPoint3: "आधुनिक प्रविधि",
    missionPoint3Desc: "हामी सटीक पढाइका लागि प्राचीन ज्ञानलाई अत्याधुनिक प्रविधिसँग जोड्छौं।",
    valuesTitle: "हाम्रा मूल्यहरू",
    valuesSubtitle: "निर्वाण ज्योतिषमा हामीले गर्ने सबै कामलाई निर्देशन गर्ने सिद्धान्तहरू।",
    value1Title: "प्रामाणिकता",
    value1Desc: "हामी छल-कपट बिना वास्तविक, अनुसन्धान-आधारित ज्योतिषीय अन्तर्दृष्टिहरू प्रदान गर्छौं।",
    value2Title: "सुलभता",
    value2Desc: "पृष्ठभूमि वा अनुभवको परवाह नगरी सबैको लागि ब्रह्माण्डीय ज्ञान उपलब्ध गराउनु।",
    value3Title: "सम्मान",
    value3Desc: "प्राचीन परम्पराहरू र आधुनिक वैज्ञानिक समझदारी दुबैलाई सम्मान गर्नु।",
    teamTitle: "हाम्रो टोलीसँग भेट्नुहोस्",
    teamSubtitle: "निर्वाण ज्योतिषको पछाडि रहेका उत्साही ज्योतिषीहरू र विकासकर्ताहरू।",
    teamMember1: "डा. अञ्जली शर्मा",
    teamRole1: "प्रमुख ज्योतिषी",
    teamDesc1: "वैदिक ज्योतिष र ग्रहीय विज्ञानमा २०+ वर्षको अनुभव।",
    teamMember2: "माइकल जन्सन",
    teamRole2: "प्रविधि निर्देशक",
    teamDesc2: "ज्योतिषीय गणनाहरूका लागि AI र मेसिन लर्निङमा विशेषज्ञ।",
    teamMember3: "रवि कुमार",
    teamRole3: "सांस्कृतिक सल्लाहकार",
    teamDesc3: "पारम्परिक ज्योतिषीय अभ्यास र सांस्कृतिक व्याख्यामा विशेषज्ञ।",
    aboutCtaTitle: "तपाईंको यात्रा सुरु गर्न तयार हुनुहुन्छ?",
    aboutCtaSubtitle: "ताराहरूसँग जोडिनुहोस् र आज नै आफ्नो ब्रह्माण्डीय भाग्य खोज्नुहोस्।",
    spiritualJourney: "आध्यात्मिक यात्रा",
    spiritualJourneyDesc: "हाम्रा प्राचीन अभ्यासहरूको माध्यमबाट ब्रह्माण्डीय ज्ञान र आध्यात्मिक ज्ञानोदय बीचको गहिरो सम्बन्ध खोज्नुहोस्।",
    
    // Contact Us Page
    contactTitle: "हामीसँग सम्पर्क गर्नुहोस्",
    contactSubtitle: "व्यक्तिगत ज्योतिषीय मार्गदर्शन र सहयोगका लागि हाम्रा ब्रह्माण्डीय गाइडहरूसँग सम्पर्क गर्नुहोस्।",
    email: "इमेल",
    phone: "फोन",
    address: "ठेगाना",
    sendMessage: "सन्देश पठाउनुहोस्",
    sendMessageDesc: "तपाईंको ब्रह्माण्डीय यात्राका बारेमा प्रश्नहरू छन्? हामी ताराहरूको माध्यमबाट तपाईंलाई मार्गदर्शन गर्न यहाँ छौं।",
    firstName: "पहिलो नाम",
    lastName: "अन्तिम नाम",
    firstNamePlaceholder: "आफ्नो पहिलो नाम प्रविष्ट गर्नुहोस्",
    lastNamePlaceholder: "आफ्नो अन्तिम नाम प्रविष्ट गर्नुहोस्",
    emailPlaceholder: "आफ्नो इमेल ठेगाना प्रविष्ट गर्नुहोस्",
    subject: "विषय",
    subjectPlaceholder: "हामी तपाईंलाई कसरी मद्दत गर्न सक्छौं?",
    message: "सन्देश",
    messagePlaceholder: "हामीलाई तपाईंका ब्रह्माण्डीय प्रश्नहरूका बारेमा बताउनुहोस्...",
    
    // Help Center Page
    helpCenterTitle: "सहयोग केन्द्र",
    helpCenterSubtitle: "तपाईंका प्रश्नहरूका उत्तरहरू फेला पार्नुहोस् र तपाईंको ब्रह्माण्डीय यात्राका लागि आवश्यक सहयोग प्राप्त गर्नुहोस्।",
    frequentlyAskedQuestions: "बारम्बार सोधिने प्रश्नहरू",
    faqSubtitle: "हाम्रा ज्योतिषीय सेवाहरूका बारेमा सामान्य प्रश्नहरूका तुरुन्त उत्तरहरू फेला पार्नुहोस्।",
    stillNeedHelp: "अझै पनि सहयोग चाहिन्छ?",
    contactSupportDesc: "तपाईंले खोजिरहेका कुरा फेला पार्न सक्नुभएन? हाम्रो ब्रह्माण्डीय सहयोग टोली ताराहरूको माध्यमबाट नेविगेट गर्न तपाईंलाई मद्दत गर्न यहाँ छ।",
    emailSupport: "इमेल सहयोग",
    
    // FAQ Content
    faq1Question: "तपाईंका ज्योतिषीय भविष्यवाणीहरू कति सटीक छन्?",
    faq1Answer: "हाम्रा भविष्यवाणीहरू पारम्परिक वैदिक ज्योतिष सिद्धान्तहरू र आधुनिक खगोलीय डेटाको संयोजनमा आधारित छन्। हामी सटीकताका लागि प्रयास गर्छौं, तर ज्योतिष एक मार्गदर्शन उपकरण हो र यसलाई तपाईंको आफ्नो अन्तर्ज्ञान र निर्णय लिने क्षमतासँग प्रयोग गर्नुपर्छ।",
    faq2Question: "कुण्डली विश्लेषणका लागि मलाई कुन जानकारी प्रदान गर्नुपर्छ?",
    faq2Answer: "सटीक कुण्डली विश्लेषणका लागि, हामीलाई तपाईंको जन्म मिति, जन्म समय, र जन्म स्थान चाहिन्छ। जन्म समय जति सटीक हुन्छ, तपाईंको चार्ट पनि त्यति सटीक हुन्छ।",
    faq3Question: "मैले कति बेर आफ्नो राशिफल जाँच गर्नुपर्छ?",
    faq3Answer: "दैनिक राशिफलहरूले दिनका लागि सामान्य मार्गदर्शन प्रदान गर्छन्। प्रमुख जीवन निर्णयहरूका लागि, हामी तपाईंको विस्तृत जन्म चार्ट र ग्रहीय ट्रान्जिटहरू विचार गर्न सल्लाह दिन्छौं।",
    faq4Question: "के मैले वास्तविक ज्योतिषीसँग परामर्श प्राप्त गर्न सक्छु?",
    faq4Answer: "हो! हामी प्रमाणित वैदिक ज्योतिषीहरूसँग व्यक्तिगत परामर्श प्रदान गर्छौं। तपाईं हाम्रो सम्पर्क फर्मको माध्यमबाट सत्र बुक गर्न सक्नुहुन्छ वा तुरुन्त सहयोगका लागि हाम्रो AI ब्रह्माण्डीय गाइडसँग कुराकानी गर्न सक्नुहुन्छ।",
    faq5Question: "के मेरो व्यक्तिगत जानकारी सुरक्षित छ?",
    faq5Answer: "बिल्कुल। हामी तपाईंको व्यक्तिगत डेटा र जन्म जानकारीलाई सुरक्षा गर्न उद्योग-मानक इन्क्रिप्शन प्रयोग गर्छौं। तपाईंको गोपनीयता हाम्रो सर्वोच्च प्राथमिकता हो।",
    faq6Question: "वैदिक र पश्चिमी ज्योतिष बीच कुन फरक छ?",
    faq6Answer: "वैदिक ज्योतिषले साइडरियल राशिचक्र प्रयोग गर्छ र चन्द्रमाको स्थितिमा केन्द्रित हुन्छ, जबकि पश्चिमी ज्योतिषले ट्रपिकल राशिचक्र प्रयोग गर्छ। वैदिक ज्योतिष अधिक पारम्परिक र आध्यात्मिक रूपमा केन्द्रित हुन्छ।",
    faq7Question: "मैले आफ्नो जन्म चार्ट कसरी व्याख्या गर्ने?",
    faq7Answer: "हाम्रो विस्तृत कुण्डली विश्लेषणले प्रत्येक ग्रहको स्थिति र प्रभावका लागि व्याख्याहरू प्रदान गर्छ। हामी तपाईंले आफ्नो ब्रह्माण्डीय ब्लूप्रिन्ट बुझ्न मद्दत गर्न निर्देशित व्याख्याहरू पनि प्रदान गर्छौं।",
    faq8Question: "के ज्योतिषले भविष्य भविष्यवाणी गर्न सक्छ?",
    faq8Answer: "ज्योतिषले सम्भावित प्रवृत्तिहरू र प्रभावहरूका बारेमा अन्तर्दृष्टि प्रदान गर्छ, तर यसले निश्चित परिणामहरू भविष्यवाणी गर्दैन। यो ब्रह्माण्डीय ऊर्जाहरू बुझ्न र सूचित निर्णय लिने उपकरण हो।",
    
    // Privacy Policy Page
    privacyPolicyTitle: "गोपनीयता नीति",
    privacyPolicySubtitle: "तपाईंको गोपनीयता हाम्रो लागि महत्वपूर्ण छ। हामी कसरी तपाईंको व्यक्तिगत जानकारी सङ्कलन, प्रयोग र सुरक्षा गर्छौं भन्ने बारेमा जान्नुहोस्।",
    lastUpdated: "अन्तिम अपडेट",
    informationWeCollect: "हामी सङ्कलन गर्ने जानकारी",
    informationWeCollectDesc: "हामी तपाईंले हामीलाई प्रत्यक्ष रूपमा प्रदान गर्ने जानकारी सङ्कलन गर्छौं, जस्तै जब तपाईंले खाता सिर्जना गर्नुहुन्छ, हाम्रा सेवाहरू प्रयोग गर्नुहुन्छ, वा सहयोगका लागि हामीसँग सम्पर्क गर्नुहुन्छ।",
    personalInfo: "व्यक्तिगत जानकारी (नाम, इमेल, जन्म विवरण)",
    usageData: "प्रयोग डेटा र सेवा अन्तरक्रियाहरू",
    cookiesData: "कुकीज र समान ट्र्याकिङ प्रविधिहरू",
    communicationData: "हाम्रो सहयोग टोलीसँग कुराकानीहरू",
    howWeUseInfo: "हामी तपाईंको जानकारी कसरी प्रयोग गर्छौं",
    howWeUseInfoDesc: "हामी सङ्कलन गर्ने जानकारीलाई हाम्रा ज्योतिषीय सेवाहरू प्रदान, राखराख र सुधार गर्न प्रयोग गर्छौं।",
    serviceProvision: "व्यक्तिगत ज्योतिषीय सेवाहरू प्रदान गर्नुहोस्",
    communication: "हाम्रा सेवाहरूका बारेमा तपाईंसँग कुराकानी गर्नुहोस्",
    improvement: "सुधार र नयाँ सुविधाहरू विकास गर्नुहोस्",
    legalCompliance: "कानूनी दायित्वहरू पूरा गर्नुहोस्",
    dataProtection: "डेटा सुरक्षा",
    dataProtectionDesc: "हामी तपाईंको व्यक्तिगत जानकारीलाई अनधिकृत पहुँच, परिवर्तन, प्रकटीकरण, वा विनाशबाट सुरक्षा गर्न उपयुक्त सुरक्षा उपायहरू कार्यान्वयन गर्छौं।",
    encryption: "संवेदनशील डेटाका लागि अन्त-देखि-अन्त इन्क्रिप्शन",
    secureServers: "नियमित सुरक्षा अपडेटहरूसहित सुरक्षित सर्भरहरू",
    accessControl: "अधिकृत कर्मचारीहरूमात्र सीमित पहुँच",
    regularAudits: "नियमित सुरक्षा लेखापरीक्षा र मूल्याङ्कनहरू",
    yourRights: "तपाईंका अधिकारहरू",
    yourRightsDesc: "तपाईंको व्यक्तिगत जानकारीका बारेमा तपाईंका केही अधिकारहरू छन्, जसमा तपाईंको डेटा पहुँच, सुधार, वा मेटाउने अधिकार समावेश छ।",
    accessData: "तपाईंको व्यक्तिगत डेटा पहुँच गर्नुहोस्",
    correctData: "गलत जानकारी सुधार गर्नुहोस्",
    deleteData: "तपाईंको खाता र डेटा मेटाउनुहोस्",
    dataPortability: "तपाईंको डेटा पोर्टेबल ढाँचामा निर्यात गर्नुहोस्",
    privacyContactDesc: "यदि तपाईंको यस गोपनीयता नीतिका बारेमा कुनै प्रश्नहरू छन्, कृपया हामीसँग सम्पर्क गर्नुहोस्।",
    
    // Terms of Service Page
    termsOfServiceTitle: "सेवा सर्तहरू",
    termsOfServiceSubtitle: "हाम्रा ज्योतिषीय सेवाहरू प्रयोग गर्नु अघि कृपया यी सर्तहरू ध्यानपूर्वक पढ्नुहोस्।",
    acceptanceOfTerms: "सर्तहरूको स्वीकृति",
    acceptanceOfTermsDesc: "निर्वाण ज्योतिष सेवाहरू पहुँच र प्रयोग गरेर, तपाईंले यस सम्झौताका सर्तहरू र प्रावधानहरूबाट बाध्य हुन स्वीकार र सहमत हुनुहुन्छ।",
    serviceDescription: "सेवा विवरण",
    serviceDescriptionDesc: "निर्वाण ज्योतिषले हाम्रो डिजिटल प्लेटफर्मको माध्यमबाट राशिफल पढाइ, कुण्डली विश्लेषण, र ब्रह्माण्डीय मार्गदर्शन सहित ज्योतिषीय सेवाहरू प्रदान गर्छ।",
    astrologicalServices: "व्यक्तिगत राशिफल पढाइहरू",
    horoscopeReadings: "दैनिक, साप्ताहिक, र मासिक भविष्यवाणीहरू",
    kundliAnalysis: "विस्तृत जन्म चार्ट विश्लेषण",
    cosmicGuidance: "AI-शक्ति प्राप्त ज्योतिषीय परामर्शहरू",
    userObligations: "प्रयोगकर्ता दायित्वहरू",
    userObligationsDesc: "प्रयोगकर्ताहरू सटीक जानकारी प्रदान गर्न र यी सर्तहरूका अनुसार हाम्रा सेवाहरू प्रयोग गर्न जिम्मेवार छन्।",
    accurateInfo: "सटीक जन्म जानकारी प्रदान गर्नुहोस्",
    respectfulUse: "सेवाहरू सम्मानपूर्वक र जिम्मेवारीपूर्वक प्रयोग गर्नुहोस्",
    noMisuse: "हाम्रो प्लेटफर्म दुरुपयोग वा दुर्व्यवहार नगर्नुहोस्",
    complianceWithLaws: "लागू कानून र नियमहरूको अनुपालन गर्नुहोस्",
    limitationOfLiability: "दायित्व सीमा",
    limitationOfLiabilityDesc: "हाम्रा ज्योतिषीय सेवाहरू केवल मार्गदर्शन उद्देश्यका लागि हुन्। हामी हाम्रा भविष्यवाणीहरू वा सल्लाहहरूको आधारमा लिइने कुनै पनि निर्णयहरूका लागि जिम्मेवार छैनौं।",
    modifications: "परिवर्तनहरू",
    modificationsDesc: "हामी कुनै पनि समयमा यी सर्तहरू परिवर्तन गर्नको अधिकार राख्छौं। हाम्रा सेवाहरूको निरन्तर प्रयोगले कुनै पनि परिवर्तनहरूको स्वीकृतिलाई जनाउँछ।",
    termsContactDesc: "यदि तपाईंको यी सेवा सर्तहरूका बारेमा प्रश्नहरू छन्, कृपया हामीसँग सम्पर्क गर्नुहोस्।",
    
    // AstroClock Page
    astroClock: "ज्योतिष घडी",
    astroClockTitle: "हिन्दू समय घडी",
    astroClockSubtitle: "पारम्परिक वैदिक समय गणना घटी, पल, र विपल मापनहरूसहित।",
    currentAstrologicalTime: "वर्तमान हिन्दू समय",
    realTimePlanetaryPositions: "वास्तविक समय वैदिक समय गणना",
    darkMode: "अँध्यारो मोड",
    hinduPeriods: "हिन्दू अवधिहरू",
    dayNight: "दिन/रात",
    digitalTime: "डिजिटल समय",
    ghatiPalVipal: "घटी:पल:विपल",
    currentPeriod: "वर्तमान अवधि",
    sunriseUjjain: "सूर्योदय (उज्जैन)",
    vedicTimeSystem: "वैदिक समय प्रणाली",
    vedicTimeSystemDesc: "सूर्योदय गणनाहरूमा आधारित घटी (२४ मिनेट), पल (२४ सेकेन्ड), र विपल (०.४ सेकेन्ड) प्रयोग गरेर पारम्परिक हिन्दू समय गणना।",
    ujjainCoordinates: "उज्जैन निर्देशाङ्क",
    ujjainCoordinatesDesc: "उज्जैन (२३.१७९३°N, ७५.७८४९१२°E) को लागि गणना गरिएको, हिन्दू ज्योतिष र समय गणनाको पारम्परिक केन्द्र।",
    sacredTimePeriods: "पवित्र समय अवधिहरू",
    sacredTimePeriodsDesc: "उषा (भोर) देखि त्रियामा (रात) सम्मका आठ पारम्परिक हिन्दू समय अवधिहरू, प्रत्येकको आध्यात्मिक महत्व र अनुष्ठान र ध्यानका लागि।",
    ushaa: "उषा",
    purvaanha: "पूर्वाह्न",
    madhyaanha: "मध्याह्न",
    aparaahnha: "अपराह्न",
    saayankala: "सायंकाल",
    pradosha: "प्रदोष",
    nishitha: "निशिथ",
    triyaama: "त्रियामा",
    dawn: "भोर",
    morning: "बिहान",
    midday: "दिउँसो",
    afternoon: "अपराह्न",
    evening: "साँझ",
    dusk: "साँझ",
    midnight: "मध्यरात",
    lateNight: "रात",
    angles: "कोणहरू",
    sunPosition: "सूर्य स्थिति",
    sunPositionDesc: "राशिचक्रमा सूर्यको वर्तमान स्थिति र यसको ज्योतिषीय महत्व।",
    moonPhase: "चन्द्रमा चरण",
    moonPhaseDesc: "वर्तमान चन्द्र चरण र यसको ब्रह्माण्डीय ऊर्जा र भावनाहरूमा प्रभाव।",
    planetaryTransits: "ग्रहीय ट्रान्जिटहरू",
    planetaryTransitsDesc: "सबै ग्रहहरूको वास्तविक समय स्थितिहरू र तिनीहरूका वर्तमान ज्योतिषीय प्रभावहरू।"
  },
  
  fi: {
    // Navbar
    home: "Koti",
    kundli: "Kundli",
    horoscope: "Horoskooppi",
    calendar: "Kalenteri",
    weather: "Sää",
    astroChat: "Astro Chat",
    about: "Tietoa",
    
    // Hero Section
    heroSubtitle: "Kosminen sukellus",
    heroTitle: "Nirvana Astro",
    heroDescription: "Avaa tähtien salaisuudet henkilökohtaisella astrologialla, päivittäisillä horoskoopeilla ja asiantuntijaohjauksella.",
    astroBot: "Astro Bot",
    astroKundli: "Astro Kundli",
    
    // Features
    featuresEyebrow: "Palvelut",
    featuresTitle: "Astrologiset palvelut",
    featuresSubtitle: "Kattavat työkalut kosmiselle matkallesi",
    
    // Feature Cards
    personalizedKundli: "Henkilökohtainen Kundli",
    personalizedKundliDesc: "Luo yksityiskohtaisia syntymäkarttoja tarkkoine planeettojen sijainteineen ja talojen sijoittelujen.",
    dailyHoroscope: "Päivittäinen horoskooppi",
    dailyHoroscopeDesc: "Saa henkilökohtaisia päivittäisiä ennusteita horoskooppimerkkisi ja planeettojen siirtymien perusteella.",
    astroChatFeature: "Astro Chat",
    astroChatDesc: "Yhdistä sertifioituihin astrologeihin henkilökohtaista ohjausta ja konsultaatioita varten.",
    compatibility: "Yhteensopivuus",
    compatibilityDesc: "Analysoi suhteen yhteensopivuutta yksityiskohtaisten synastry- ja composite-karttojen kautta.",
    panchang: "Panchang",
    panchangDesc: "Pääse hyvänsuovaisiin aikoihin, juhliin ja kuukalenteriin perinteisellä tarkkuudella.",
    remedies: "Parannuskeinot",
    remediesDesc: "Löydä henkilökohtaisia parannuskeinoja, mantroja ja jalokivisuosituksia.",
    learnMore: "Lue lisää",
    
    // Zodiac Signs
    zodiacEyebrow: "Eläinrata",
    zodiacTitle: "Tutustu 12 merkkiin",
    zodiacSubtitle: "Valitse merkki nähdäksesi sen päivittäisen tilanteen",
    aries: "Oinas",
    taurus: "Härkä",
    gemini: "Kaksoset",
    cancer: "Rapu",
    leo: "Leijona",
    virgo: "Neitsyt",
    libra: "Vaaka",
    scorpio: "Skorpioni",
    sagittarius: "Jousimies",
    capricorn: "Kauris",
    aquarius: "Vesimies",
    pisces: "Kalat",
    
    // CTA Section
    ctaTitle: "Aloita kosminen matkasi",
    ctaSubtitle: "Chattaa Astro Botin kanssa tai luo Kundlisi",
    startChat: "Aloita chat",
    generateKundli: "Luo Kundli",
    
    // Footer
    footerDescription: "Porttisi kosmiseen viisautteen. Yhdistä tähtiin henkilökohtaisen astrologian, horoskooppien ja asiantuntijaohjauksen kautta.",
    services: "Palvelut",
    support: "Tuki",
    helpCenter: "Ohjekeskus",
    contactUs: "Ota yhteyttä",
    privacyPolicy: "Tietosuojakäytäntö",
    termsOfService: "Käyttöehdot",
    faq: "Usein kysytyt kysymykset",
    copyright: "Kaikki oikeudet pidätetään. Tutki kosmosta kanssamme!",
    
    // Chat Widget
    cosmicGuide: "Kosminen opas",
    online: "Verkossa",
    askAboutStars: "Kysy tähtistäsi...",
    namasteGreeting: "Namaste! Olen kosminen opas. Kysy minulta mitä tahansa astrologiasta, horoskoopeista tai syntymäkartastasi! ✨",
    
    // About Page
    aboutTitle: "Tietoa Nirvana Astro",
    aboutSubtitle: "Porttisi kosmiseen viisautteen ja henkilökohtaiseen astrologiseen ohjaukseen.",
    missionTitle: "Meidän tehtävämme",
    missionDescription: "Uskomme, että tähdet pitävät avaimen itsensä ja paikkamme ymmärtämiseen maailmankaikkeudessa. Tehtävämme on tehdä muinainen astrologinen viisaus kaikkien saavutettavissa modernin teknologian avulla.",
    missionPoint1: "Henkilökohtainen ohjaus",
    missionPoint1Desc: "Jokainen lukeminen on räätälöity ainutlaatuiseen syntymäkarttaasi ja elämäntilanteeseesi.",
    missionPoint2: "Asiantuntija-astrologit",
    missionPoint2Desc: "Tiimimme koostuu sertifioiduista astrologeista, joilla on vuosikymmenten kokemus.",
    missionPoint3: "Moderni teknologia",
    missionPoint3Desc: "Yhdistämme muinaisen viisauden huipputeknologiaan tarkkoja lukemia varten.",
    valuesTitle: "Arvomme",
    valuesSubtitle: "Periaatteet, jotka ohjaavat kaikkea mitä teemme Nirvana Astrossa.",
    value1Title: "Aitous",
    value1Desc: "Tarjoamme aitoja, tutkimukseen perustuvia astrologisia oivalluksia ilman temppuja.",
    value2Title: "Saavutettavuus",
    value2Desc: "Kosminen viisaus kaikkien saatavilla, riippumatta taustasta tai kokemuksesta.",
    value3Title: "Kunnioitus",
    value3Desc: "Kunnioitamme sekä muinaisia perinteitä että modernia tieteellistä ymmärrystä.",
    teamTitle: "Tutustu tiimiimme",
    teamSubtitle: "Intoimiset astrologit ja kehittäjät Nirvana Astron takana.",
    teamMember1: "Dr. Anjali Sharma",
    teamRole1: "Pääastrologi",
    teamDesc1: "20+ vuoden kokemus vedisestä astrologiasta ja planeettatieteestä.",
    teamMember2: "Michael Johnson",
    teamRole2: "Teknologiajohtaja",
    teamDesc2: "Asiantuntija AI:ssa ja koneoppimisessa astrologisissa laskelmissa.",
    teamMember3: "Ravi Kumar",
    teamRole3: "Kulttuurineuvoja",
    teamDesc3: "Asiantuntija perinteisissä astrologisissa käytännöissä ja kulttuurisessa tulkinnassa.",
    aboutCtaTitle: "Valmis aloittamaan matkasi?",
    aboutCtaSubtitle: "Yhdistä tähtiin ja löydä kosminen kohtalosi tänään.",
    spiritualJourney: "Henkinen matka",
    spiritualJourneyDesc: "Löydä syvä yhteys kosmisen viisauden ja henkisen valaistumisen väliltä muinaisten käytäntöjemme kautta.",
    
    // Contact Us Page
    contactTitle: "Ota yhteyttä",
    contactSubtitle: "Ota yhteyttä kosmisia oppaamme saadaksesi henkilökohtaista astrologista ohjausta ja tukea.",
    email: "Sähköposti",
    phone: "Puhelin",
    address: "Osoite",
    sendMessage: "Lähetä viesti",
    sendMessageDesc: "Onko kysymyksiä kosmisesta matkastasi? Olemme täällä auttamassa sinua navigoimaan tähtien kautta.",
    firstName: "Etunimi",
    lastName: "Sukunimi",
    firstNamePlaceholder: "Syötä etunimesi",
    lastNamePlaceholder: "Syötä sukunimesi",
    emailPlaceholder: "Syötä sähköpostiosoitteesi",
    subject: "Aihe",
    subjectPlaceholder: "Miten voimme auttaa sinua?",
    message: "Viesti",
    messagePlaceholder: "Kerro meille kosmisista kysymyksistäsi...",
    
    // Help Center Page
    helpCenterTitle: "Ohjekeskus",
    helpCenterSubtitle: "Löydä vastauksia kysymyksiisi ja saa tarvitsemasi tuki kosmiselle matkallesi.",
    frequentlyAskedQuestions: "Usein kysytyt kysymykset",
    faqSubtitle: "Löydä nopeita vastauksia yleisiin kysymyksiin astrologisista palveluistamme.",
    stillNeedHelp: "Tarvitsetko vielä apua?",
    contactSupportDesc: "Etkö löytänyt etsimääsi? Kosminen tukitiimimme on täällä auttamassa sinua navigoimaan tähtien kautta.",
    emailSupport: "Sähköpostituki",
    
    // FAQ Content
    faq1Question: "Kuinka tarkkoja astrologiset ennusteet ovat?",
    faq1Answer: "Ennusteemme perustuvat perinteisiin vedisiin astrologian periaatteisiin yhdistettynä moderniin tähtitieteelliseen dataan. Pyrimme tarkkuuteen, mutta astrologia on ohjaustyökalu ja sitä tulisi käyttää oman intuitiosi ja päätöksentekokykysi rinnalla.",
    faq2Question: "Mitä tietoja tarvitsen Kundli-analyysiä varten?",
    faq2Answer: "Tarkkaa Kundli-analyysiä varten tarvitsemme syntymäpäiväsi, syntymäaikasi ja syntymäpaikkasi. Mitä tarkempi syntymäaika on, sitä tarkempi karttasi on.",
    faq3Question: "Kuinka usein horoskoppini pitäisi tarkistaa?",
    faq3Answer: "Päivittäiset horoskoopit tarjoavat yleistä ohjausta päivälle. Suurten elämänpäätösten osalta suosittelemme konsultoimaan yksityiskohtaista syntymäkarttaasi ja harkitsemaan planeettien transiitteja.",
    faq4Question: "Voinko saada konsultaation oikean astrologin kanssa?",
    faq4Answer: "Kyllä! Tarjoamme henkilökohtaisia konsultaatioita sertifioitujen vedisten astrologien kanssa. Voit varata istunnon yhteydenottolomakkeemme kautta tai chattailla AI-kosmisoppaamme kanssa välittömään apuun.",
    faq5Question: "Onko henkilötietoni turvassa?",
    faq5Answer: "Ehdottomasti. Käytämme alan standardeja noudattavaa salausmenetelmää henkilötietojesi ja syntymätietojesi suojaamiseen. Yksityisyytesi on ykkösprioriteettimme.",
    faq6Question: "Mikä on ero vedisen ja länsimaisen astrologian välillä?",
    faq6Answer: "Vedinen astrologia käyttää sideraalista eläinrataa ja keskittyy kuun asemaan, kun länsimainen astrologia käyttää trooppista eläinrataa. Vedinen astrologia on perinteisempi ja henkisesti suuntautunut.",
    faq7Question: "Miten tulkitsen syntymäkarttani?",
    faq7Answer: "Yksityiskohtainen Kundli-analyysimme tarjoaa selityksiä jokaisen planeetan asemalle ja vaikutukselle. Tarjoamme myös ohjattuja tulkintoja auttamaan sinua ymmärtämään kosmisen sinettisi.",
    faq8Question: "Voiko astrologia ennustaa tulevaisuutta?",
    faq8Answer: "Astrologia tarjoaa näkemyksiä mahdollisista trendeistä ja vaikutuksista, mutta se ei ennusta kiinteitä lopputuloksia. Se on työkalu kosmisten energioiden ymmärtämiseen ja informoitujen päätösten tekemiseen.",
    
    // Privacy Policy Page
    privacyPolicyTitle: "Tietosuojakäytäntö",
    privacyPolicySubtitle: "Yksityisyytesi on meille tärkeää. Opi, miten keräämme, käytämme ja suojaamme henkilötietojasi.",
    lastUpdated: "Viimeksi päivitetty",
    informationWeCollect: "Keräämämme tiedot",
    informationWeCollectDesc: "Keräämme tietoja, jotka annat meille suoraan, kuten kun luot tilin, käytät palveluitamme tai otat yhteyttä tukeen.",
    personalInfo: "Henkilötiedot (nimi, sähköposti, syntymätiedot)",
    usageData: "Käyttötiedot ja palveluinteraktiot",
    cookiesData: "Evästeet ja vastaavat seurantateknologiat",
    communicationData: "Viestintä tukitiimimme kanssa",
    howWeUseInfo: "Miten käytämme tietojasi",
    howWeUseInfoDesc: "Käytämme keräämiämme tietoja astrologisten palveluidemme tarjoamiseen, ylläpitoon ja parantamiseen.",
    serviceProvision: "Tarjota henkilökohtaisia astrologisia palveluja",
    communication: "Kommunikoida kanssasi palveluistamme",
    improvement: "Parantaa ja kehittää uusia ominaisuuksia",
    legalCompliance: "Noudattaa lakisääteisiä velvollisuuksia",
    dataProtection: "Tietosuoja",
    dataProtectionDesc: "Toteutamme asianmukaisia turvallisuustoimenpiteitä henkilötietojesi suojaamiseksi luvattomalta pääsyltä, muutokselta, paljastumiselta tai tuhoutumiselta.",
    encryption: "Päästä päähän salaus arkaluontoisille tiedoille",
    secureServers: "Turvalliset palvelimet säännöllisillä turvallisuuspäivityksillä",
    accessControl: "Rajoitettu pääsy vain valtuutetuille henkilöille",
    regularAudits: "Säännölliset turvallisuusauditoinnit ja arvioinnit",
    yourRights: "Oikeutesi",
    yourRightsDesc: "Sinulla on tietyt oikeudet henkilötietoihisi liittyen, mukaan lukien oikeus käyttää, korjata tai poistaa tietojasi.",
    accessData: "Käyttää henkilötietojasi",
    correctData: "Korjata virheellisiä tietoja",
    deleteData: "Poistaa tilisi ja tietosi",
    dataPortability: "Viedä tietosi siirrettävässä muodossa",
    privacyContactDesc: "Jos sinulla on kysymyksiä tästä tietosuojakäytännöstä, ota yhteyttä meihin.",
    
    // Terms of Service Page
    termsOfServiceTitle: "Käyttöehdot",
    termsOfServiceSubtitle: "Lue nämä ehdot huolellisesti ennen astrologisten palveluidemme käyttöä.",
    acceptanceOfTerms: "Ehtojen hyväksyminen",
    acceptanceOfTermsDesc: "Käyttämällä Nirvana Astro -palveluita hyväksyt ja sitoudut noudattamaan tämän sopimuksen ehtoja ja määräyksiä.",
    serviceDescription: "Palvelun kuvaus",
    serviceDescriptionDesc: "Nirvana Astro tarjoaa astrologisia palveluja, mukaan lukien horoskooppilukuja, Kundli-analyysiä ja kosmista ohjausta digitaalisen alustamme kautta.",
    astrologicalServices: "Henkilökohtaiset horoskooppilukut",
    horoscopeReadings: "Päivittäiset, viikoittaiset ja kuukausittaiset ennusteet",
    kundliAnalysis: "Yksityiskohtainen syntymäkartta-analyysi",
    cosmicGuidance: "AI-käyttöiset astrologiset konsultaatiot",
    userObligations: "Käyttäjän velvollisuudet",
    userObligationsDesc: "Käyttäjät vastaavat tarkkojen tietojen antamisesta ja palveluidemme käyttämisestä näiden ehtojen mukaisesti.",
    accurateInfo: "Antaa tarkkoja syntymätietoja",
    respectfulUse: "Käyttää palveluja kunnioittavasti ja vastuullisesti",
    noMisuse: "Ei väärinkäytä tai väärinkäytä alustaamme",
    complianceWithLaws: "Noudattaa soveltuvia lakeja ja määräyksiä",
    limitationOfLiability: "Vastuun rajoitus",
    limitationOfLiabilityDesc: "Astrologiset palvelumme ovat vain ohjaustarkoitukseen. Emme ole vastuussa päätöksistä, jotka tehdään ennusteidemme tai neuvomme perusteella.",
    modifications: "Muutokset",
    modificationsDesc: "Pidätämme oikeuden muuttaa näitä ehtoja milloin tahansa. Palveluidemme jatkuva käyttö merkitsee muutosten hyväksymistä.",
    termsContactDesc: "Jos sinulla on kysymyksiä näistä käyttöehdoista, ota yhteyttä meihin.",
    
    // AstroClock Page
    astroClock: "Astro Kellot",
    astroClockTitle: "Hindu Kellot",
    astroClockSubtitle: "Perinteinen vedalainen aikamittaus Ghati, Pal ja Vipal mittauksilla.",
    currentAstrologicalTime: "Nykyinen Hindu Aika",
    realTimePlanetaryPositions: "Reaaliaikainen vedalainen aikamittaus",
    darkMode: "Tumma Tila",
    hinduPeriods: "Hindu Jaksot",
    dayNight: "Päivä/Yö",
    digitalTime: "Digitaalinen Aika",
    ghatiPalVipal: "Ghati:Pal:Vipal",
    currentPeriod: "Nykyinen Jakso",
    sunriseUjjain: "Auringonnousu (Ujjain)",
    vedicTimeSystem: "Vedalainen Aikajärjestelmä",
    vedicTimeSystemDesc: "Perinteinen hindulainen aikamittaus käyttäen Ghati (24 minuuttia), Pal (24 sekuntia) ja Vipal (0.4 sekuntia) auringonnousu laskelmien perusteella.",
    ujjainCoordinates: "Ujjain Koordinaatit",
    ujjainCoordinatesDesc: "Laskettu Ujjainille (23.1793°N, 75.784912°E), perinteinen hindulaisen astrologian ja aikamittauksen keskus.",
    sacredTimePeriods: "Pyhät Aikajaksot",
    sacredTimePeriodsDesc: "Kahdeksan perinteistä hindulaista aikajaksoa Ushaasta (aamunkoitto) Triyaamaan (myöhäinen yö), jokaisella oma hengellinen merkityksensä rituaaleille ja meditaatiolle.",
    ushaa: "Ushaa",
    purvaanha: "Purvaanha",
    madhyaanha: "Madhyaanha",
    aparaahnha: "Aparaahnha",
    saayankala: "Saayankala",
    pradosha: "Pradosha",
    nishitha: "Nishitha",
    triyaama: "Triyaama",
    dawn: "Aamunkoitto",
    morning: "Aamu",
    midday: "Keskipäivä",
    afternoon: "Iltapäivä",
    evening: "Ilta",
    dusk: "Ilta",
    midnight: "Keskiyö",
    lateNight: "Myöhäinen Yö",
    angles: "Kulmat",
    sunPosition: "Auringon asema",
    sunPositionDesc: "Auringon nykyinen asema eläinradassa ja sen astrologinen merkitys.",
    moonPhase: "Kuun vaihe",
    moonPhaseDesc: "Nykyinen kuun vaihe ja sen vaikutus kosmisiin energioihin ja tunteisiin.",
    planetaryTransits: "Planeettien transiitit",
    planetaryTransitsDesc: "Kaikkien planeettojen reaaliaikaiset asemat ja niiden nykyiset astrologiset vaikutukset."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('nirvana-astro-language');
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('nirvana-astro-language', newLanguage);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
